### ISSUE TITLE
TODO(back-end): errors

### ISSUE THREAD

**Issue by svmnotn** [svmnotn/upgraded-pancake#9]
Add errors to the library side, then make use of them in the server.

- [x] Add Error Type to the lib
- [x] Use Error whenever error's would occur
- [x] Handle the errors in the server
- [x] Properly forward the relevant errors to the front-end
- [x] See how serde erros are sent to the front-end
- [x] Properly forward them to the front-end
- [x] Cleanup the error forwarding code
- [x] Update the docs to account for errors
- [x] Add all the missing descriptions to the docs
